# Generated by Django 4.0.3 on 2022-04-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('amount', models.CharField(max_length=30)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_item', to='recipes.fooditem')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure', to='recipes.measure')),
            ],
        ),
    ]
