# Generated by Django 4.0.3 on 2022-04-20 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredient_recipe_alter_ingredient_food_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='recipes.fooditem'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='recipes.measure'),
        ),
    ]
