# Generated by Django 4.0.3 on 2022-04-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredient_food_item_alter_ingredient_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
